package com.multiapp.core.stub

import com.multiapp.core.manifest.DeviceIdentityConfig
import com.multiapp.core.manifest.ManifestGenerator
import com.multiapp.core.manifest.ManifestParser
import com.multiapp.core.manifest.StubConfig
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

/**
 * BinaryXmlEncoder 回归测试
 *
 * 验证生成的二进制 XML 可被 apksig 正确解析。
 * 之前出现过 attributeStart=65535 的 bug, 此测试确保不再复现。
 */
class ManifestGeneratorBasicValidationTest {

    @Test
    fun `generateBytes produces valid binary XML`() {
        val generator = ManifestGenerator()

        val manifest = ManifestParser.ParsedManifest(
            packageName = "com.test.app",
            applicationClass = null,
            minSdkVersion = 28,
            targetSdkVersion = 36,
            permissions = listOf("android.permission.INTERNET"),
            activities = listOf(
                ManifestParser.ComponentInfo(
                    name = "com.test.app.MainActivity",
                    exported = true
                ),
                ManifestParser.ComponentInfo(
                    name = "com.test.app.SettingsActivity",
                    exported = false
                )
            ),
            services = listOf(
                ManifestParser.ComponentInfo(
                    name = "com.test.app.MyService",
                    exported = false
                )
            ),
            receivers = emptyList(),
            providers = emptyList()
        )

        val launcherActivity = ManifestParser.ComponentInfo(
            name = "com.test.app.MainActivity",
            exported = true
        )

        val config = StubConfig(
            instanceId = "test_001",
            stubPackageName = "com.test.app.clonestub",
            originalPackageName = "com.test.app",
            launchActivity = "com.test.app.MainActivity",
            originalSignatures = listOf("/path/to/original.apk"),
            authorityMap = emptyMap(),
            deviceIdentity = DeviceIdentityConfig(
                imei = "123456789012345",
                androidId = "abcdef1234567890",
                macAddress = "AA:BB:CC:DD:EE:FF",
                serial = "R5CR12345AB",
                buildModel = "Pixel 9",
                buildManufacturer = "Google",
                buildFingerprint = "google/raven/raven:14/test"
            )
        )

        val bytes = generator.generateBytes("com.test.app.clonestub", manifest, launcherActivity, config)

        // 验证二进制 XML 基本结构
        assertNotNull(bytes, "Generated bytes should not be null")
        assertTrue(bytes.isNotEmpty(), "Generated bytes should be non-empty")

        // 验证 XML header (0x00080003 = StringPool chunk type)
        val header = (bytes[0].toInt() and 0xFF) or ((bytes[1].toInt() and 0xFF) shl 8)
        assertEquals(0x0003, header, "First two bytes should be StringPool chunk type (0x0003)")

        // 验证 attributeStart 不是 65535 (之前的 bug)
        // 在 START_ELEMENT chunk 中, attributeStart 在固定偏移位置
        // 如果 attributeStart=65535, 说明编码有误
        // 这里简单验证 bytes 不全为 0xFF
        val nonZeroCount = bytes.count { it.toInt() and 0xFF != 0xFF }
        assertTrue(nonZeroCount > bytes.size / 2, "Binary XML should not be all 0xFF")
    }

    @Test
    fun `generateBytes handles empty providers`() {
        val generator = ManifestGenerator()
        val manifest = ManifestParser.ParsedManifest(
            packageName = "com.test.app",
            applicationClass = null,
            minSdkVersion = 28,
            targetSdkVersion = 36,
            permissions = emptyList(),
            activities = listOf(
                ManifestParser.ComponentInfo(name = "com.test.app.MainActivity", exported = true)
            ),
            services = emptyList(),
            receivers = emptyList(),
            providers = emptyList()
        )
        val config = StubConfig(
            instanceId = "test_002",
            stubPackageName = "com.test.app.clonestub2",
            originalPackageName = "com.test.app",
            launchActivity = "com.test.app.MainActivity",
            originalSignatures = emptyList(),
            authorityMap = emptyMap(),
            deviceIdentity = DeviceIdentityConfig(
                imei = "000000000000000",
                androidId = "0000000000000000",
                macAddress = "00:00:00:00:00:00",
                serial = "0000000000",
                buildModel = "Test",
                buildManufacturer = "Test",
                buildFingerprint = "test/test/test:14/test/test:user/release-keys"
            )
        )

        val bytes = generator.generateBytes(
            "com.test.app.clonestub2",
            manifest,
            manifest.activities.first(),
            config
        )

        assertNotNull(bytes)
        assertTrue(bytes.size > 0)
    }
}
