package com.multiapp.core.engine.ipc;

import android.os.Bundle;
import android.os.IBinder;
import android.os.ParcelFileDescriptor;

interface IEngineRuntimeService {
    String getServerGenerationId();
    Bundle engineInstallOrRefreshPackage(String originPackageName);
    Bundle engineCreateInstance(String originPackageName);
    Bundle engineCreateInstanceWithMetadata(in Bundle request);
    Bundle engineLaunchInstance(in Bundle request);
    Bundle engineStopInstance(String instanceId);
    Bundle engineDeleteInstance(String instanceId);
    Bundle engineQueryRuntimeState(String instanceId);
    ParcelFileDescriptor engineOpenRuntimeState(String instanceId, in Bundle request);
    Bundle engineExportEvidence(String instanceId);
    Bundle attachClient(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, int processId, IBinder clientToken);
    Bundle processRestarted(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, int processId, IBinder clientToken);
    Bundle markProcessPrewarmed(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, int processId);
    Bundle abandonProcessClient(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, int processId, String reason);
    Bundle issueRecentsRestoreCapability(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, int processId, String restoreActivityId);
    Bundle queryRuntime(String instanceId);
    Bundle queryRuntimeByProcessId(int processId);
    Bundle resolveUriPermissionCheckTarget(String callerInstanceId, int targetProcessId);
    Bundle prepareComponentProcess(String instanceId, String guestProcessName);
    Bundle attachComponentProcessClient(String attachCapability, IBinder clientToken);
    Bundle queryComponentProcessClient(String instanceId, String guestProcessName);
    Bundle queryCallingComponentProcess(String instanceId);
    Bundle queryApplicationEnabledState(String instanceId, in Bundle request);
    Bundle setApplicationEnabledState(String instanceId, in Bundle request);
    Bundle queryComponentEnabledState(String instanceId, in Bundle request);
    Bundle setComponentEnabledState(String instanceId, in Bundle request);
    Bundle authorizeActivityLaunch(String capabilityToken, String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, String proxyActivityClassName, String guestActivityClassName);
    Bundle acknowledgeActivityResumed(String instanceId, long runtimeEpoch, String engineSessionId, String processSlot, String capabilityToken);
    Bundle queryEvidence(String instanceId);
    Bundle planActivity(String instanceId, in Bundle request);
    Bundle allocateActivityLaunch(String instanceId, in Bundle request);
    boolean releaseActivityLaunch(String instanceId, in Bundle allocation);
    boolean recordActivityDispatch(String instanceId, in Bundle result);
    Bundle mutateActivity(String instanceId, String operation, in Bundle request);
    Bundle consumeActivity(String instanceId, String operation, in Bundle request);
    Bundle syncActivityTaskState(String instanceId, String reason, in Bundle snapshot);
    Bundle queryActivityTaskState(String instanceId);
    Bundle queryProxyActivitySlot(in Bundle request);
    Bundle reserveProxyActivitySlot(in Bundle request);
    Bundle compareAndSetProxyActivitySlot(in Bundle request);
    Bundle resolveProviderAuthority(String callerInstanceId, in Bundle request);
    Bundle issueProviderRouteToken(String callerInstanceId, in Bundle request);
    Bundle validateAndConsumeProviderRouteToken(String targetInstanceId, in Bundle request);
    Bundle planProvider(String instanceId, in Bundle request);
    boolean recordProviderDispatch(String instanceId, in Bundle result);
    Bundle queryProviderRuntimeState(String instanceId);
    Bundle grantProviderUriPermission(String ownerInstanceId, in Bundle request);
    Bundle revokeProviderUriPermission(String ownerInstanceId, in Bundle request);
    Bundle checkProviderUriPermission(String targetInstanceId, in Bundle request);
    Bundle checkProviderUriPermissionForCaller(String callerInstanceId, String targetInstanceId, in Bundle request);
    Bundle takePersistableProviderUriPermission(String targetInstanceId, in Bundle request);
    Bundle releasePersistableProviderUriPermission(String targetInstanceId, in Bundle request);
    Bundle checkPermission(String instanceId, String permissionName);
    Bundle queryPermissionRuntimeState(String instanceId);
    Bundle queryAppOp(String instanceId, in Bundle request);
    Bundle planService(String instanceId, in Bundle request);
    boolean recordServiceDispatch(String instanceId, in Bundle result);
    Bundle queryServiceRuntimeState(String instanceId);
    Bundle registerServiceConnection(String instanceId, in Bundle operationLease, IBinder connectionToken);
    Bundle queryServiceConnection(String instanceId, IBinder connectionToken);
    Bundle removeServiceConnectionBinding(String instanceId, in Bundle binding, IBinder connectionToken);
    Bundle removeServiceConnection(String instanceId, IBinder connectionToken);
    Bundle planBroadcast(String instanceId, in Bundle request);
    boolean recordBroadcastDispatch(String instanceId, in Bundle result);
    Bundle queryBroadcastRuntimeState(String instanceId);
    boolean recordOperationEvidence(String instanceId, in Bundle evidence);
    boolean stopRuntime(String instanceId, long runtimeEpoch);
    Bundle engineQueryCapabilities(String instanceId);
    Bundle engineClearInstanceData(String instanceId);
    Bundle engineRefreshPackage(in Bundle request);
}
